# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89dffa7be8ef7828e2cd8e1820bdd39c5e2a9a3e2743f8f73aa8a81df806091285be57cea5f27fa1c3682e441ead14307516bcf77571f481a2abf0178f554a06

test:
  secret_key_base: de690ad4c7993736d1644af8c628fb4dafcf6f229daf11698e0b40340f53a8e6c92569608d34ac4b50b0c6f75745ead9c446eb63c4199c57848bcb278ac3714f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
